In [39]:
# list , dictinary, tuple
myList =[20,30,40,50,70]
myList[3:]

[50, 70]

In [10]:
dict={"raghu":"trainer","mahi":"player","guru"}
dict["mahi"]
dict.keys()

SyntaxError: ':' expected after dictionary key (4228875426.py, line 1)

In [20]:
students = {"s_1":["IBM"], "s_2" : ["infy","wipro","google"]}
students["s_2"][2]

'google'

In [8]:
tup_ex = (1,2,3,4,4,2,)
mylist= [1,2,3,4,5]
mylist.append(7)
mylist
#in list we can add elements 
#tuples are not mutable

[1, 2, 3, 4, 5, 7]

#this is for text

In [15]:
!conda  install pandas

Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

In [11]:
from pandas import read_csv
import pandas as pd 
df=pd.read_csv("Data Collection.csv")

In [20]:
df.head(n=10)

         Date      Time      Location Number Plate
0  01-01-2024   8:00 AM      New York      ABC1234
1  01-01-2024   9:15 AM   Los Angeles      XYZ5678
2  01-01-2024  10:30 AM       Chicago      DEF9101
3  02-01-2024   8:45 AM       Houston      GHI2345
4  02-01-2024   9:00 AM         Miami      JKL6789
5  02-01-2024  10:15 AM       Phoenix      MNO0123
6  03-01-2024   8:30 AM  Philadelphia      PQR4567
7  03-01-2024   9:45 AM   San Antonio      STU8901
8  03-01-2024  11:00 AM     San Diego      VWX2345
9  04-01-2024   7:50 AM        Dallas      YZA6789

In [44]:
df.tail()

          Date      Time         Location Number Plate
70  24-01-2024   9:45 AM       Evansville      ZAB0123
71  24-01-2024  10:00 AM  West Palm Beach      CDE4567
72  25-01-2024   8:15 AM     Fort Collins      FGH8901
73  25-01-2024   9:30 AM          Roanoke      IJK2345
74  25-01-2024  10:45 AM   Salt Lake City      LMN6789

In [ ]:
df["START*"]

In [26]:
temp= pd.DataFrame({"A":[1,2,3],"B":[11,22,33],"C":["12-3-2024","13-4-2024","13-5-2024"]})

In [42]:
temp.dtypes
temp["A"] = pd.to_numeric(temp["A"])